import type { Metadata } from "next";
import "@/style/globals.css";
import { notoSansThai } from "@/style/font";

import Layout from "@/component/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className={`${notoSansThai.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
